apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: autoscaling-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: autoscaling-alerts
      rules:

        - alert: HPAMaxReplicasReached
          expr: kube_horizontalpodautoscaler_status_current_replicas == kube_horizontalpodautoscaler_spec_max_replicas
          for: 5m
          labels:
            severity: warning
            service: hpa
            namespace: monitoring
          annotations:
            summary: HPA reached maximum replicas
            description: HPA has been running at its maximum replica count for 5 minutes.