fullnameOverride: tempo

deploymentMode: SingleBinary

singleBinary:
  replicas: 1

tempo:
  reportingEnabled: false
  retention: 24h

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal

persistence:
  enabled: true
  storageClassName: standard-rwo
  size: 5Gi

service:
  type: ClusterIP

serviceMonitor:
  enabled: true

lokiSearch:
  enabled: true
  datasourceUid: loki