deploymentMode: SingleBinary

tempo:
  reportingEnabled: false

  receivers:
    otlp:
      protocols:
        grpc:
        http:

server:
  http_listen_port: 3200

singleBinary:
  replicas: 1

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal

persistence:
  enabled: true
  size: 10Gi

service:
  type: ClusterIP

lokiSearch:
  enabled: true
  datasourceUid: loki