apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: order-app
  labels:
    app: inventory-service
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: inventory-service

  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      securityContext:
        runAsNonRoot: true

      containers:
        - name: inventory-service
          image: asia-south1-docker.pkg.dev/iconic-being-499605-m3/order-app/inventory-service:v7

          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8001
              protocol: TCP

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL