apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: order-app
  labels:
    app: inventory-service
spec:
  type: ClusterIP

  selector:
    app: inventory-service

  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP